"""empty message

Revision ID: 414cf5fe99b9
Revises: 139c3f7f5a5f
Create Date: 2019-06-25 22:23:07.341780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414cf5fe99b9'
down_revision = '139c3f7f5a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
